services:
  node_api:
    image: node:alpine
    depends_on:
      - postgresdb
      - pgadmin
    ports:
      - "3030:3030"
    volumes:
      - ".:/sondages"
    environment:
      NODE_ENV: development
      SERVER_PORT: 3030
      PG_DATABASE_URL: postgresql://postgres:secret@postgresdb:5432/sondages?schema=public&connection_limit=5

  postgresdb:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sondages

  pgadmin:
    image: adminer
    ports:
      - "5050:8080"
    environment:
      ADMINER_DESIGN: mvt
      ADMINER_DEFAULT_SERVER: postgresdb
