services:
  node_api:
    image: node:alpine
    depends_on:
      - postgresdb
      - pgadmin
    ports:
      - "3030:3030"
    volumes:
      - ".:/sondages"

  postgresdb:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: sondages

  pgadmin:
    image: adminer
    ports:
      - "5050:8080"
    environment:
        ADMINER_DESIGN: mvt
        ADMINER_DEFAULT_SERVER: postgresdb
