services:
  node_api:
    image: sondages:prod
    depends_on:
      - postgresdb
    ports:
      - "8010:80"
    volumes:
      - ".:/sondages"
    environment:
      NODE_ENV: production
      SERVER_PORT: 80
      CORS_ORIGIN:
      PG_DATABASE_URL:
      DATABASE_HOST:
      DATABASE_USER:
      PGPASSWORD:

  postgresdb:
    image: postgres:alpine
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "5"
    environment:
      POSTGRES_USER:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
